apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: acrvincentstodolist1.azurecr.io/todo-backend:v14
        imagePullPolicy: Always # IfNotPresent (For local images in Minikube), Always (for AKS)
        ports:
        - containerPort: 3001
        envFrom:
        - secretRef:
            name: mongodb-secret
        env:
        - name: ALLOWED_ORIGIN
          value: "*"  # Set to "*" for Minikube development; Replace with the actual frontend URL when deploying to the cloud (i.e. production)
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
spec:
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP # Use LoadBalancer for external access (production); Use NodePort for external access (development); Use ClusterIP for internal (cluster) communication