apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://armatoor_db_user_2:Spiderman123456!@mycluster.h4cpmu4.mongodb.net/?appName=MyCluster"